#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Get PHP version.
#======================================================================================================================

cd /tmp

VERSION=$(cat PHP_BUILD)
bf-echo "PHP version ${VERSION}."


#======================================================================================================================
# Install PHP dependencies and packages.
#   (bash is required for php.ini configuration.)
#======================================================================================================================

bf-echo "Installing dependencies..."
apk add --no-cache \
    bash
bf-done

bf-echo "Installing PHP v${VERSION}..."
chmod +x ./install-php && ./install-php ${VERSION}
bf-done

bf-echo "Creating blank error log..."
touch ${PHP_INI_ERROR_LOG}
bf-done


#======================================================================================================================
# Cleanup.
#======================================================================================================================

bf-echo "Cleanup /www files."
rm -f /www/index.html
