FROM bcgdesign/nginx:auto

LABEL maintainer="Ben Green <ben@bcgdesign.com>" \
    org.label-schema.name="Nginx + PHP" \
    org.label-schema.version="latest" \
    org.label-schema.vendor="Ben Green" \
    org.label-schema.schema-version="1.0"

ENV \
    # www.conf override: log_level
    PHP_FPM_LOG_LEVEL="notice" \
    # php.ini template to use
    PHP_INI="production" \
    # php.ini override: display_errors
    PHP_INI_DISPLAY_ERRORS= \
    # php.ini override: display_startup_errors
    PHP_INI_DISPLAY_STARTUP_ERRORS= \
    # php.ini override: error_log
    PHP_INI_ERROR_LOG="/var/log/php8/error.log" \
    # php.ini override: err-r_reporting
    PHP_INI_ERROR_REPORTING= \
    # php.ini override: memory_limit
    PHP_INI_MEMORY_LIMIT="256M" \
    # php.ini override: max_post
    PHP_INI_MAX_POST="64M" \
    # php.ini override: max_upload
    PHP_INI_MAX_UPLOAD="64M" \
    # php.ini override: session_max_lifetime
    PHP_SESSION_MAX_LIFETIME=86400

ENV PHP_DIR=/etc/php8

COPY ./8.0/PHP_BUILD /tmp/PHP_BUILD
RUN export PHP_VERSION=$(cat /tmp/PHP_BUILD) \
    && echo "PHP v${PHP_VERSION}" \
    && apk -U upgrade \
    && apk add \
        bash \
        php8=${PHP_VERSION} \
        php8-common=${PHP_VERSION} \
        php8-fpm=${PHP_VERSION} \
        php8-session=${PHP_VERSION} \
    && ln -s /usr/bin/php8 /usr/bin/php \
    && rm -rf /var/cache/apk/* /www/* /tmp/*

COPY ./overlay /
COPY ./overlay-nginx-conf /etc/nginx/http.d
COPY ./8.0/php-fpm /etc/services.d/php-fpm
