#!/usr/bin/with-contenv bash

#======================================================================================================================
# From https://wiki.alpinelinux.org/wiki/Nginx_with_PHP#PHP7_Installation
#======================================================================================================================

echo " - overriding www.conf configuration values..."

declare -A VALUES
VALUES["listen.owner"]="www"
VALUES["listen.group"]="www"
VALUES["listen.mode"]="0660"
VALUES["user"]="www"
VALUES["group"]="www"
VALUES["log_level"]="notice"

source "/etc/functions/replace.sh"
replace $VALUES "/etc/php7/php-fpm.d/www.conf"

echo " - done."
