#!/usr/bin/with-contenv bash

#======================================================================================================================
# Includes https://wiki.alpinelinux.org/wiki/Nginx_with_PHP#PHP7_Installation
#
# Modifications copyright (c) 2020 Ben Green <https://bcgdesign.com>
#======================================================================================================================


#======================================================================================================================
# Get php.ini 
#======================================================================================================================

if [ "$PHP_INI" == "development" ] || [ "$PHP_INI" == "production" ] ; then
    URL="https://github.com/php/php-src/blob/master/php.ini-$PHP_INI"
    curl -L -o "$URL" "/etc/php7/php.ini"
fi


#======================================================================================================================
# Optionally override configuration
#======================================================================================================================

if [ ! -z "$PHP_DISPLAY_ERRORS" ] ; then
    sed -i "s|display_errors\s*=\s*Off|display_errors = $PHP_DISPLAY_ERRORS|i" /etc/php7/php.ini
fi

if [ ! -z "$PHP_DISPLAY_STARTUP_ERRORS" ] ; then
    sed -i "s|display_startup_errors\s*=\s*Off|display_startup_errors = $PHP_DISPLAY_STARTUP_ERRORS|i" /etc/php7/php.ini
fi

if [ ! -z "$PHP_ERROR_REPORTING" ] ; then
    sed -i "s|error_reporting\s*=\s*E_ALL & ~E_DEPRECATED & ~E_STRICT|error_reporting = $PHP_ERROR_REPORTING|i" /etc/php7/php.ini
fi

if [ ! -z "$PHP_MEMORY_LIMIT" ] ; then
    sed -i "s|;*memory_limit =.*|memory_limit = $PHP_MEMORY_LIMIT|i" /etc/php7/php.ini
fi

if [ ! -z "$PHP_MAX_UPLOAD" ] ; then
    sed -i "s|;*upload_max_filesize =.*|upload_max_filesize = $PHP_MAX_UPLOAD|i" /etc/php7/php.ini
fi

if [ ! -z "$PHP_MAX_POST" ] ; then
    sed -i "s|;*post_max_size =.*|post_max_size = $PHP_MAX_POST|i" /etc/php7/php.ini
fi
