#!/usr/bin/with-contenv bash

#======================================================================================================================
# Get php.ini 
#======================================================================================================================

if [ "$PHP_INI" == "development" ] || [ "$PHP_INI" == "production" ] ; then
    URL="https://raw.githubusercontent.com/php/php-src/master/php.ini-$PHP_INI"
    echo " - downloading php.ini from $URL..."
    curl -Ls -o "/etc/php7/php.ini" "$URL"
    echo " - done."
fi


#======================================================================================================================
# Optionally override configuration
#======================================================================================================================

echo " - overriding php.ini configuration values..."

declare -A VALUES
VALUES["display_errors"]="$PHP_DISPLAY_ERRORS"
VALUES["display_startup_errors"]="$PHP_DISPLAY_STARTUP_ERRORS"
VALUES["error_reporting"]="$PHP_ERROR_REPORTING"
VALUES["memory_limit"]="$PHP_MEMORY_LIMIT"
VALUES["upload_max_filesize"]="$PHP_MAX_UPLOAD"
VALUES["post_max_size"]="$PHP_MAX_POST"

source "/etc/functions/replace.sh"
replace VALUES "/etc/php7/php.ini"

echo " - done."
