#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

# Library configuration
bf-env "PHP_LIB" "${BCG_LIB}/php"
