#!/usr/bin/with-contenv bash

#======================================================================================================================
# Optionally override configuration
#======================================================================================================================

_echo "setting www.conf configuration values..."

declare -A VALUES
VALUES["listen.owner"]="www"
VALUES["listen.group"]="www"
VALUES["listen.mode"]="0660"
VALUES["user"]="www"
VALUES["group"]="www"
VALUES["log_level"]="${PHP_FPM_LOG_LEVEL}"

source /etc/functions/replace.sh
replace VALUES "/etc/php7/php-fpm.d/www.conf"

_done
