#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Optionally override configuration
#======================================================================================================================

bcg-echo "Setting www.conf configuration values..."

declare -A VALUES
VALUES["user"]="www"
VALUES["group"]="www"
VALUES["log_level"]="${PHP_FPM_LOG_LEVEL-}"

source /etc/functions/replace.sh
replace VALUES "${PHP_DIR}/php-fpm.d/www.conf"

bcg-done
