#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Get php.ini
#======================================================================================================================

DOWNLOADED="${PHP_DIR}/php.ini-${PHP_INI}.downloaded"
if [ -e ${DOWNLOADED} ] ; then
    _ok "php.ini already downloaded."
    exit 0
fi

if [ "${PHP_INI}" = "development" ] || [ "${PHP_INI}" = "production" ] ; then

    URL="https://raw.githubusercontent.com/php/php-src/master/php.ini-${PHP_INI}"
    _echo "Downloading php.ini from ${URL}..."
    wget -O "${PHP_DIR}/php.ini" ${URL} \
        && touch ${DOWNLOADED}
    _done

else

    _error "Unsupported PHP_INI value: '${PHP_INI}'."

fi
