#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Optionally override configuration.
#======================================================================================================================

bf-echo "Setting www.conf configuration values..."

declare -A VALUES
VALUES["user"]="www"
VALUES["group"]="www"
VALUES["log_level"]="${PHP_FPM_LOG_LEVEL-}"

source ${BF_INC}/php-replace-ini.sh
replace-ini VALUES ${PHP_DIR}/php-fpm.d/www.conf

bf-done
