#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E="php-error-log/$(basename ${0})"


#======================================================================================================================
# Forward PHP errors to Docker.
#======================================================================================================================

bcg-forward php-error-log ${PHP_INI_ERROR_LOG}
