#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E="php-fpm/$(basename ${0})"


#======================================================================================================================
# Start PHP FastCGI Process Manager.
#
# php-fpm8 flags
#   -F  run in foreground mode (allows S6 to supervise the service)
#======================================================================================================================

VERSION=$(php -r "echo PHP_VERSION;")
bcg-echo "Starting PHP v${VERSION} - FastCGI Process Manager"
php-fpm7 -F
