#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Hat-tip https://www.getpagespeed.com/server-setup/php/cleanup-php-sessions-like-a-pro.
#======================================================================================================================

bf-echo "Cleaning PHP sessions..."
php \
    -d session.gc_probability=1 \
    -d session.gc_divisor=1 \
    -d session.gc_maxlifetime=${PHP_SESSION_MAX_LIFETIME} \
    -r "session_start(); session_destroy();"
bf-done
