#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Start PHP FastCGI Process Manager
#   -F  run in foreground mode (allows S6 to supervise the service)
#======================================================================================================================

_echo "Starting PHP FastCGI Process Manager"
php-fpm8 -F
