name: 8.0-main

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/build_8_0-main.yml'
      - '8.0/**'
      - 'overlay/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read PHP version - major
        uses: bencgreen/read-file-action@v1
        with:
          path: ./8.0/PHP_MAJOR
        id: php_major
      -
        name: Read PHP version - minor
        uses: bencgreen/read-file-action@v1
        with:
          path: ./8.0/PHP_MINOR
        id: php_minor
      -
        name: Read PHP version - revision
        uses: bencgreen/read-file-action@v1
        with:
          path: ./8.0/PHP_REVISION
        id: php_revision
      -
        name: Read PHP version - build
        uses: bencgreen/read-file-action@v1
        with:
          path: ./8.0/PHP_BUILD
        id: php_build
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./8.0/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          #platforms: linux/amd64,linux/arm/v7
          #platforms: linux/amd64,linux/arm64
          tags: |
            bcgdesign/nginx-php:php-${{ steps.php_major.outputs.content }}
            bcgdesign/nginx-php:php-${{ steps.php_minor.outputs.content }}
            bcgdesign/nginx-php:php-${{ steps.php_revision.outputs.content }}
            bcgdesign/nginx-php:php-${{ steps.php_build.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
