name: 8.0-dev

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/build_8_0-main.yml'
      - '8.0/**'
      - 'overlay/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./8.0/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          #platforms: linux/amd64,linux/arm/v7
          #platforms: linux/amd64,linux/arm64
          tags: |
            bcgdesign/nginx-php:dev
            bcgdesign/nginx-php:dev-php-8.0
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
