name: publish-8_0-edge

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-8_0-edge:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read PHP version - revision
        uses: bencgreen/read-file-action@v1
        with:
          path: ./8.0-edge/PHP_REVISION
        id: php_revision
      -
        name: Read PHP version - build
        uses: bencgreen/read-file-action@v1
        with:
          path: ./8.0-edge/PHP_BUILD
        id: php_build
      -
        name: Read image version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./8.0-edge/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bcgdesign/nginx-php:php8-edge
            bcgdesign/nginx-php:php8-edge-${{ steps.version.outputs.content }}
            bcgdesign/nginx-php:php8.0-edge
            bcgdesign/nginx-php:php8.0-edge-${{ steps.version.outputs.content }}
            bcgdesign/nginx-php:php${{ steps.php_revision.outputs.content }}-edge
            bcgdesign/nginx-php:php${{ steps.php_build.outputs.content }}-edge
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
